# This is a basic workflow to help you get started with Actions

name: UnityBuild-Automation

# Controls when the workflow will run
on: workflow_dispatch

env:
  UNITY_DIR: "C:/Program Files/Unity/Hub/Editor/2020.3.3f1/Editor/Unity.exe"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Windows
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a Build
        run: $UNITY_DIR -xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' unity-editor -projectPath='.' -quit -batchmode -nographics -executeMethod SuperUnityBuild.BuildTool.BuildCLI.PerformBuild
