# This is a basic workflow to help you get started with Actions

# This is a basic workflow to help you get started with Actions

name: UnityBuild-Automation

# Controls when the workflow will run
on: workflow_dispatch



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Windows
    strategy:
      fail-fast: false
      
    defaults:
      run:
        shell: cmd
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
         
      
      # Runs a set of commands using the runners shell
      - name: Remove Cache Build
        run: if exist Builds rmdir /q /s Builds
      
      - name: Build Solution
        run: |      
            "C:\Program Files\Unity\Hub\Editor\2020.3.3f1\Editor\Unity.exe" -xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' unity-editor -projectPath='.' -quit -batchmode -nographics -executeMethod UnityEditor.SyncVS.SyncSolution
      
      - name: Run a Build
        run: |
            "C:\Program Files\Unity\Hub\Editor\2020.3.3f1\Editor\Unity.exe" -xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' unity-editor -projectPath='.' -quit -batchmode -nographics -executeMethod SuperUnityBuild.BuildTool.BuildCLI.PerformBuild
        
      - name: Export
        uses: actions/upload-artifact@v3
        with:
          name: Build-Result
          path: Builds/*