name: UnityBuild-Import

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Import:
    # The type of runner that the job will run on
    runs-on: Windows
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove Cache Build
        run: |
            $Folder = '.\Builds'
            If(Test-Path -Path $Folder) {Remove-Item –path $Folder -include * –recurse}
            
      - name: Run a Import
        run: Start-Process -NoNewWindow -FilePath "C:/Program Files/Unity/Hub/Editor/2020.3.3f1/Editor/Unity.exe" -ArgumentList "-quit -batchmode -nographics -projectpath '.' -buildWindowsPlayer 'Builds/result.exe'"