name: UnityBuild-Import

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Import:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2020.3.3f1-android-1.0.1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
         
      
      # Runs a set of commands using the runners shell
      - name: Remove Cache Build
        run: (if [ -d "Builds" ]; then rm -rf ./Builds/*; else mkdir ./Builds; fi);
      
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2020.3.3f1
          targetPlatform: Android
          allowDirtyBuild: true
          buildMethod: SuperUnityBuild.BuildTool.BuildCLI.PerformBuild
      
      - name: Build Solution
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |      
            /opt/unity/Editor/Unity -xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' unity-editor -projectPath='.' -quit -batchmode -nographics -executeMethod UnityEditor.SyncVS.SyncSolution
      
      - name: Run a Build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
            /opt/unity/Editor/Unity -xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' unity-editor -projectPath='.' -quit -batchmode -nographics -executeMethod SuperUnityBuild.BuildTool.BuildCLI.PerformBuild
        
      - name: Export
        uses: actions/upload-artifact@v3
        with:
          name: Build-Result
          path: Builds/*